### ISSUE TITLE
Lorentz vectors, particle PDG, jet-clustering, oh my! -> some problems with examples

### ISSUE THREAD

**Issue by JacekHoleczek** [hsf-training/hsf-training-scikit-hep-webpage#55]
I've met some problems with the examples in the "[`Lorentz vectors, particle PDG, jet-clustering, oh my!`](https://hsf-training.github.io/hsf-training-scikit-hep-webpage/06-lorentz-vectors/index.html)" chapter.

In the "`Particle PDG`" and "`Jet clustering`" sections:
`particle.Particle.from_string("p~")`
and:
`probable_mass = particle.Particle.from_string("pi+").mass / GeV`
generate warnings in the form:
`<stdin>:1: DeprecationWarning: Call to deprecated class method from_string. (This method is deprecated and will be removed from version 0.23.0. Use finditer or findall instead.) -- Deprecated since version 0.22.`

In the "`Jet clustering`" section, in the "fastjet" example:

```text
>>> good_pseudojets = pseudojets[pseudojets.pt > 0.1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/storage/home/holeczek/micromamba/envs/tutorial/lib/python3.11/site-packages/awkward/highlevel.py", line 1108, in __getattr__
    raise AttributeError(f"no field named {where!r}")
AttributeError: no field named 'pt'. Did you mean: 'px'?
```

Then I cannot "`import jetset`" ... and when I try to "`install jetset`", I get:

```text
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ fastjet does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

**Comment by jpivarski** [comment]
> Then I cannot "`import jetset`"

I don't know what "jetset" is. Do you mean `fastjet`?

> AttributeError: no field named 'pt'. Did you mean: 'px'?

It sounds like an array of Lorentz vectors was loaded without

```python
vector.register_awkward()
```

> Call to deprecated class method from_string.

Again, the tutorial is showing its age. If Particle is deprecating `from_string`, it should be replaced with `finditer` or `findall`. Both of these allow for the possibility of multiple matches. Maybe

```python
particle.Particle.from_string("pi+")
```

should become

```python
next(particle.Particle.finditer("pi+"))
```

(to bake-in the assumption that there's only one, or we're only interested in the first)?

**Comment by eduardo-rodrigues** [comment]
See also https://github.com/scikit-hep/particle#getting-started-particles and of course the extensive docstrings :-).

**Comment by jpivarski** [comment]
Sorry, I get GitHub notifications via email, which can be out of date.

On fastjet in conda-forge—you're right, it's not done: scikit-hep/fastjet#133.
